# ***Python para Análise de Dados (Pandas)***

--------------------------------------------------------------------------------------------------

## ***Importando a Biblioteca Pandas***

--------------------------------------------------------------------------------------------------

Primeiro passo é importar a bibloteca 'Pandas' e o apelidando como 'pd'

In [14]:
import pandas as pd
import os

Criamos um dataframe (conjunto de dados, semelhante ao Excel com linhas e colunas) como 'df'. 

Uma vez que o utilizamos, estaremos dizendo o Python para ele =  "sempre ler esse arquivo, que esta em tal caminho e traga ele aqui"

In [19]:
df = pd.read_csv('../datasets/Gapminder.csv', sep=';')

--------------------------------------------------------------------------------------------------

## ***Acessando os dados***

--------------------------------------------------------------------------------------------------

## ***Acessando os primeiros dados do arquvio:***

### head()

Por padrão, ele retornando as 5 primeiras linhas do arquivo.

Obs.: Como é por index, ele retorna do 0 ao 4, totalizando os 5 primeiros index.

In [20]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Caso queira que ele retorne outro número de linhas específico, coloque o número desejado dentro dos seus parênteses, o que o fará ser um parâmetro

In [25]:
df.head(11)

           Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0   Afghanistan       Asia  1952        28.801     8425333  779.445314
1   Afghanistan       Asia  1957        30.332     9240934  820.853030
2   Afghanistan       Asia  1962        31.997    10267083  853.100710
3   Afghanistan       Asia  1967        34.020    11537966  836.197138
4   Afghanistan       Asia  1972        36.088    13079460  739.981106
5   Afghanistan       Asia  1977        38.438    14880372  786.113360
6   Afghanistan       Asia  1982        39.854    12881816  978.011439
7   Afghanistan       Asia  1987        40.822    13867957  852.395945
8   Afghanistan       Asia  1992        41.674    16317921  649.341395
9   Afghanistan       Asia  1997        41.763    22227415  635.341351
10  Afghanistan       Asia  2002        42.129    25268405  726.734055

--------------------------------------------------------------------------------------------------

## ***Acessando os últimos dados do arquvio:***

### tail()

Por padrão, ele retornando as 5 últimas linhas do arquivo.

O mesmo ocorre com o head(), caso queira um número específico para retornar, coloque este dentro dos seus parâmetros.

Obs.: Como é por index, ele retorna do 0 ao 4, totalizando os 5 últimos index.

In [31]:
df.tail(11)

          Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
3301  Zimbabwe     Africa  1957        50.469     3646340  518.764268
3302  Zimbabwe     Africa  1962        52.358     4277736  527.272182
3303  Zimbabwe     Africa  1967        53.995     4995432  569.795071
3304  Zimbabwe     Africa  1972        55.635     5861135  799.362176
3305  Zimbabwe     Africa  1977        57.674     6642107  685.587682
3306  Zimbabwe     Africa  1982        60.363     7636524  788.855041
3307  Zimbabwe     Africa  1987        62.351     9216418  706.157306
3308  Zimbabwe     Africa  1992        60.377    10704340  693.420786
3309  Zimbabwe     Africa  1997        46.809    11404948  792.449960
3310  Zimbabwe     Africa  2002        39.989    11926563  672.038623
3311  Zimbabwe     Africa  2007        43.487    12311143  469.709298

Obs.: Você vê as colunas em português pois foi uma alteração que eu fiz no próximo passo

--------------------------------------------------------------------------------------------------

# ***Formatando o arquivo***

--------------------------------------------------------------------------------------------------

## ***Formatando as colunas***

### rename()

Já que as colunas estão em inglês, vamos alterar apenas elas para português.

Utilizaremos o método rename() e em seu parâmetro o 'columns' que deve aceitar os novos valores por meio da Estrutura de Dados 'Dicionário'.

*nome em inglês * : * nome em portugues *

In [21]:
df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

             Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0     Afghanistan       Asia  1952        28.801     8425333  779.445314
1     Afghanistan       Asia  1957        30.332     9240934  820.853030
2     Afghanistan       Asia  1962        31.997    10267083  853.100710
3     Afghanistan       Asia  1967        34.020    11537966  836.197138
4     Afghanistan       Asia  1972        36.088    13079460  739.981106
...           ...        ...   ...           ...         ...         ...
3307     Zimbabwe     Africa  1987        62.351     9216418  706.157306
3308     Zimbabwe     Africa  1992        60.377    10704340  693.420786
3309     Zimbabwe     Africa  1997        46.809    11404948  792.449960
3310     Zimbabwe     Africa  2002        39.989    11926563  672.038623
3311     Zimbabwe     Africa  2007        43.487    12311143  469.709298

[3312 rows x 6 columns]

--------------------------------------------------------------------------------------------------

# ***Salvando as alterações no 'df' (dataframe)***

In [26]:
# Simplismente atribua o 'df' ao códgigo de formatação feita pro você

df = df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

Testando se 'df' está alterado de fato:

In [24]:
df.head() # Sim. As 'colunas' estão em português:

          Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0  Afghanistan       Asia  1952        28.801     8425333  779.445314
1  Afghanistan       Asia  1957        30.332     9240934  820.853030
2  Afghanistan       Asia  1962        31.997    10267083  853.100710
3  Afghanistan       Asia  1967        34.020    11537966  836.197138
4  Afghanistan       Asia  1972        36.088    13079460  739.981106

--------------------------------------------------------------------------------------------------

# ***Retornando valores de um arquivo .csv***

--------------------------------------------------------------------------------------------------

## ***Retornando - Número de linhas e colunas que um arquivo possuí***

### shape

Retorna uma tupla com os valores que o arquivo dispõe.

(* número de linhas *, * número de colunas *)

Obs.: Perceba que o 'shape' não precisa dos parênteses '()' depois dele, pois ele é uma "Atributo" ou "Proriedade" (São características ou dados que já estão lá, "etiquetados". O Pandas a trata como uma propriedade de leitura rápida, não como uma ação que precisa de parâmetros extras.).

In [28]:
df.shape

(3312, 6)

--------------------------------------------------------------------------------------------------

## ***Retornando - Apenas os nomes das colunas***

### columns

Retorna uma tupla com uma lista com os valores que o arquivo dispõe e o seu tipo por último.

Obs.: Perceba que o 'columns' não precisa dos parênteses '()' depois dele, pois ele é uma "Atributo" ou "Proriedade" (São características ou dados que já estão lá, "etiquetados". O Pandas a trata como uma propriedade de leitura rápida, não como uma ação que precisa de parâmetros extras.).

In [29]:
df.columns

Index(['Pais', 'Continente', 'Ano', 'Exp. de vida', 'Pop. Total', 'PIB'], dtype='object')

## ***Retornando - Tipo de dado em cada coluna***

### dtypes

Retorna uma tabela com o nome de cada coluna e, ao lado, o seu tipo de cado que ele armazena.

Obs.: Perceba que o 'dtypes' não precisa dos parênteses '()' depois dele, pois ele é uma "Atributo" ou "Proriedade" (São características ou dados que já estão lá, "etiquetados". O Pandas a trata como uma propriedade de leitura rápida, não como uma ação que precisa de parâmetros extras.).

In [32]:
df.dtypes

Pais             object
Continente       object
Ano               int64
Exp. de vida    float64
Pop. Total        int64
PIB             float64
dtype: object

--------------------------------------------------------------------------------------------------

# ***Estatísticas***

--------------------------------------------------------------------------------------------------

## ***Estatísticas - Retornando uma descrição por meio de informações estatísicas sobre o nosso arquivo***

### describre()

Retorna uma tabela nova com essas informações, respeitando cada coluna do arquivo.

In [33]:
df.describe()

               Ano  Exp. de vida    Pop. Total            PIB
count  3312.000000   3312.000000  3.312000e+03    3312.000000
mean   1980.301630     65.246871  3.161489e+07   11317.115805
std      16.927294     11.768412  1.041193e+08   11369.142739
min    1950.000000     23.599000  5.941200e+04     241.165876
25%    1967.000000     58.337500  2.678572e+06    2514.625266
50%    1982.000000     69.610000  7.557218e+06    7838.505123
75%    1996.000000     73.657750  1.958522e+07   17357.879170
max    2007.000000     82.670000  1.318683e+09  113523.132900

--------------------------------------------------------------------------------------------------

# ***Filtragem de Dados***

--------------------------------------------------------------------------------------------------

## ***Acesso Direto***

In [ ]:
df["Continente"] # Semelhante ao 'Acesso Direto'

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
3307    Africa
3308    Africa
3309    Africa
3310    Africa
3311    Africa
Name: Continente, Length: 3312, dtype: object

## ***Quais são os valores únicos de uma coluna?***

### unique()

Quando utilizado com o 'acesso direto' podemos trazer apenas os valores únicos que existe em uma coluna.

In [36]:
df["Continente"].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', nan, 'FSU', 'Oceania'],
      dtype=object)

perceba que ele traz um 'array'. O que é um array?

Se você ouvir alguém falando de "arrays em Python" no contexto de Ciência de Dados ou Inteligência Artificial, eles estão falando da biblioteca NumPy. Esses arrays são incrivelmente rápidos e permitem cálculos matemáticos complexos em massa.

Exemplo de código com este uso:

Criando um array do NumPy:

import numpy as np

arr = np.array([1, 2, 3])
print(arr * 2)  # Multiplica todos os itens por 2 de uma vez: [2, 4, 6]

--------------------------------------------------------------------------------------------------

### nunique()

Retorna qual é o número de 'continentes' únicos dessa coluna.

In [39]:
df["Continente"].nunique()

6

--------------------------------------------------------------------------------------------------

## ***Acessando - Apenas os valores de um continente***

### loc[] - localizar

Por boas práticas, pode ser interessante armazenar esse código de acesso em uma variável.

In [37]:
oceania = df.loc[df["Continente"] == "Oceania"]

acessando a variavel 'oceania':

In [38]:
oceania.head()

     Pais Continente   Ano  Exp. de vida  Pop. Total          PIB
975  Fiji    Oceania  1962        56.494      421869  2039.393277
976  Fiji    Oceania  1967        58.607      485000  2170.073285
977  Fiji    Oceania  1972        60.642      544000  2797.759484
978  Fiji    Oceania  1977        62.669      599339  3182.569600
979  Fiji    Oceania  1982        64.683      658906  3209.257468

--------------------------------------------------------------------------------------------------

# ***Banco de Dados***

--------------------------------------------------------------------------------------------------

## ***Agrupamento de Dados***

Agrupamento de dados é muito comum em Banco de Dados. Aqui mostraremos como fazer o mesmo com o Pandas.

### groupby()

"Quantos paises nós temos para cada continente?"

In [ ]:
# 'agrupo' pelo continente, 'encontre pelo' pais e 'retorne' a soma de paises que cada um tem com nunique() 
df.groupby("Continente")["Pais"].nunique()

Continente
Africa      51
Americas    25
Asia        41
Europe      35
FSU          6
Oceania      3
Name: Pais, dtype: int64

### groupby() + mean()

"Para cada ano, qual era a 'expecitativa média de vida' de cada país? "

In [57]:
# 'agrupo' pelo ano, 'encontre pela' a exp. de vida e 'retorne' a média 
df.groupby("Ano")["Exp. de vida"].mean()

Ano
1950    62.002568
1951    65.904167
1952    49.206867
1953    66.674563
1954    67.459817
1955    67.806757
1956    67.950637
1957    51.614590
1958    68.815936
1959    68.226579
1960    68.470837
1961    68.862480
1962    54.035234
1963    69.595735
1964    70.063105
1965    70.259881
1966    70.447526
1967    56.263629
1968    70.689081
1969    70.653896
1970    70.961141
1971    71.103976
1972    58.474481
1973    71.500338
1974    71.778504
1975    71.939218
1976    72.158050
1977    60.429090
1978    72.717567
1979    73.018717
1980    73.064524
1981    73.337399
1982    62.365871
1983    73.787778
1984    74.100741
1985    74.112222
1986    74.452222
1987    63.984860
1988    74.760000
1989    74.924444
1990    74.283438
1991    74.374848
1992    65.008443
1993    74.324545
1994    74.456667
1995    74.552727
1996    75.029394
1997    65.873799
1998    75.569697
1999    75.703636
2000    76.026364
2001    76.257879
2002    66.835695
2003    76.586667
2004    76.921562
2005    76.718667
2006    77.887778
2007    67.868557
Name: Exp. de vida, dtype: float64

--------------------------------------------------------------------------------------------------

# ***Métodos úteis***

--------------------------------------------------------------------------------------------------

### sum()

Retorna a soma de uma coluna.

Obs.: Retornará apenas se o tipo de coluna que possuí o tipo de dado int / float nela.

In [61]:
df["PIB"].sum()

np.float64(37482287.5451553)

### mean()

Retorna a média de uma coluna.

Obs.: Retornará apenas se o tipo de coluna que possuí o tipo de dado int / float nela.

In [62]:
df["PIB"].mean()

np.float64(11317.115804696648)