# ***Python para Análise de Dados (Pandas)***

--------------------------------------------------------------------------------------------------

Primeiro passo é importar a bibloteca 'Pandas' e o apelidando como 'pd'

In [14]:
import pandas as pd
import os

Criamos um dataframe (conjunto de dados, semelhante ao Excel com linhas e colunas) como 'df'. 

Uma vez que o utilizamos, estaremos dizendo o Python para ele =  "sempre ler esse arquivo, que esta em tal caminho e traga ele aqui"

In [19]:
df = pd.read_csv('../datasets/Gapminder.csv', sep=';')

--------------------------------------------------------------------------------------------------

## ***Acessando os dados do arquvio:***

### head()

Por padrão, ele retornando as 5 primeiras linhas do arquivo.

Obs.: Como é por index, ele retorna do 0 ao 4, totalizando os 5 primeiros index.

In [20]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Caso queira que ele retorne outro número de linhas específico, coloque o número desejado dentro dos seus parênteses, o que o fará ser um parâmetro

In [25]:
df.head(11)

           Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0   Afghanistan       Asia  1952        28.801     8425333  779.445314
1   Afghanistan       Asia  1957        30.332     9240934  820.853030
2   Afghanistan       Asia  1962        31.997    10267083  853.100710
3   Afghanistan       Asia  1967        34.020    11537966  836.197138
4   Afghanistan       Asia  1972        36.088    13079460  739.981106
5   Afghanistan       Asia  1977        38.438    14880372  786.113360
6   Afghanistan       Asia  1982        39.854    12881816  978.011439
7   Afghanistan       Asia  1987        40.822    13867957  852.395945
8   Afghanistan       Asia  1992        41.674    16317921  649.341395
9   Afghanistan       Asia  1997        41.763    22227415  635.341351
10  Afghanistan       Asia  2002        42.129    25268405  726.734055

Obs.: Você vê as colunas em português pois foi uma alteração que eu fiz no próximo passo

--------------------------------------------------------------------------------------------------

# ***Formatando o arquivo***

Formatando as colunas:

Já que as colunas estão em inglês, vamos alterar apenas elas para português.

Utilizaremos o método rename() e em seu parâmetro o 'columns' que deve aceitar os novos valores por meio da Estrutura de Dados 'Dicionário'.

*nome em inglês * : * nome em portugues *

In [21]:
df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

             Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0     Afghanistan       Asia  1952        28.801     8425333  779.445314
1     Afghanistan       Asia  1957        30.332     9240934  820.853030
2     Afghanistan       Asia  1962        31.997    10267083  853.100710
3     Afghanistan       Asia  1967        34.020    11537966  836.197138
4     Afghanistan       Asia  1972        36.088    13079460  739.981106
...           ...        ...   ...           ...         ...         ...
3307     Zimbabwe     Africa  1987        62.351     9216418  706.157306
3308     Zimbabwe     Africa  1992        60.377    10704340  693.420786
3309     Zimbabwe     Africa  1997        46.809    11404948  792.449960
3310     Zimbabwe     Africa  2002        39.989    11926563  672.038623
3311     Zimbabwe     Africa  2007        43.487    12311143  469.709298

[3312 rows x 6 columns]

--------------------------------------------------------------------------------------------------

# ***Salvando as alterações no 'df' (dataframe)***

In [26]:
# Simplismente atribua o 'df' ao códgigo de formatação feita pro você

df = df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

Testando se 'df' está alterado de fato:

In [24]:
df.head() # Sim. As 'colunas' estão em português:

          Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0  Afghanistan       Asia  1952        28.801     8425333  779.445314
1  Afghanistan       Asia  1957        30.332     9240934  820.853030
2  Afghanistan       Asia  1962        31.997    10267083  853.100710
3  Afghanistan       Asia  1967        34.020    11537966  836.197138
4  Afghanistan       Asia  1972        36.088    13079460  739.981106

--------------------------------------------------------------------------------------------------

# ***Retornando valores de um arquivo .csv***

## ***Retornando o número de lihas e colunas que um arquivo possuí***

### shape

Retorna uma tupla com os valores que o arquivo dispõe.

(* número de linhas *, * número de colunas *)

Obs.: Perceba que o 'shape' não precisa dos parênteses '()' depois dele.

In [28]:
df.shape

(3312, 6)

--------------------------------------------------------------------------------------------------

## ***Retornando apenas os nomes das colunas***