# ***Python para Análise de Dados (Pandas)***

--------------------------------------------------------------------------------------------------

## ***Importando a Biblioteca Pandas***

--------------------------------------------------------------------------------------------------

Primeiro passo é importar a bibloteca 'Pandas' e o apelidando como 'pd'

In [14]:
import pandas as pd
import os

Criamos um dataframe (conjunto de dados, semelhante ao Excel com linhas e colunas) como 'df'. 

Uma vez que o utilizamos, estaremos dizendo o Python para ele =  "sempre ler esse arquivo, que esta em tal caminho e traga ele aqui"

In [19]:
df = pd.read_csv('../datasets/Gapminder.csv', sep=';')

--------------------------------------------------------------------------------------------------

## ***Acessando os dados***

--------------------------------------------------------------------------------------------------

## ***Acessando os primeiros dados do arquvio:***

### head()

Por padrão, ele retornando as 5 primeiras linhas do arquivo.

Obs.: Como é por index, ele retorna do 0 ao 4, totalizando os 5 primeiros index.

In [20]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Caso queira que ele retorne outro número de linhas específico, coloque o número desejado dentro dos seus parênteses, o que o fará ser um parâmetro

In [25]:
df.head(11)

           Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0   Afghanistan       Asia  1952        28.801     8425333  779.445314
1   Afghanistan       Asia  1957        30.332     9240934  820.853030
2   Afghanistan       Asia  1962        31.997    10267083  853.100710
3   Afghanistan       Asia  1967        34.020    11537966  836.197138
4   Afghanistan       Asia  1972        36.088    13079460  739.981106
5   Afghanistan       Asia  1977        38.438    14880372  786.113360
6   Afghanistan       Asia  1982        39.854    12881816  978.011439
7   Afghanistan       Asia  1987        40.822    13867957  852.395945
8   Afghanistan       Asia  1992        41.674    16317921  649.341395
9   Afghanistan       Asia  1997        41.763    22227415  635.341351
10  Afghanistan       Asia  2002        42.129    25268405  726.734055

--------------------------------------------------------------------------------------------------

## ***Acessando os últimos dados do arquvio:***

### tail()

Por padrão, ele retornando as 5 últimas linhas do arquivo.

O mesmo ocorre com o head(), caso queira um número específico para retornar, coloque este dentro dos seus parâmetros.

Obs.: Como é por index, ele retorna do 0 ao 4, totalizando os 5 últimos index.

In [31]:
df.tail(11)

          Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
3301  Zimbabwe     Africa  1957        50.469     3646340  518.764268
3302  Zimbabwe     Africa  1962        52.358     4277736  527.272182
3303  Zimbabwe     Africa  1967        53.995     4995432  569.795071
3304  Zimbabwe     Africa  1972        55.635     5861135  799.362176
3305  Zimbabwe     Africa  1977        57.674     6642107  685.587682
3306  Zimbabwe     Africa  1982        60.363     7636524  788.855041
3307  Zimbabwe     Africa  1987        62.351     9216418  706.157306
3308  Zimbabwe     Africa  1992        60.377    10704340  693.420786
3309  Zimbabwe     Africa  1997        46.809    11404948  792.449960
3310  Zimbabwe     Africa  2002        39.989    11926563  672.038623
3311  Zimbabwe     Africa  2007        43.487    12311143  469.709298

Obs.: Você vê as colunas em português pois foi uma alteração que eu fiz no próximo passo

--------------------------------------------------------------------------------------------------

# ***Formatando o arquivo***

--------------------------------------------------------------------------------------------------

## ***Formatando as colunas***

Já que as colunas estão em inglês, vamos alterar apenas elas para português.

Utilizaremos o método rename() e em seu parâmetro o 'columns' que deve aceitar os novos valores por meio da Estrutura de Dados 'Dicionário'.

*nome em inglês * : * nome em portugues *

In [21]:
df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

             Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0     Afghanistan       Asia  1952        28.801     8425333  779.445314
1     Afghanistan       Asia  1957        30.332     9240934  820.853030
2     Afghanistan       Asia  1962        31.997    10267083  853.100710
3     Afghanistan       Asia  1967        34.020    11537966  836.197138
4     Afghanistan       Asia  1972        36.088    13079460  739.981106
...           ...        ...   ...           ...         ...         ...
3307     Zimbabwe     Africa  1987        62.351     9216418  706.157306
3308     Zimbabwe     Africa  1992        60.377    10704340  693.420786
3309     Zimbabwe     Africa  1997        46.809    11404948  792.449960
3310     Zimbabwe     Africa  2002        39.989    11926563  672.038623
3311     Zimbabwe     Africa  2007        43.487    12311143  469.709298

[3312 rows x 6 columns]

--------------------------------------------------------------------------------------------------

# ***Salvando as alterações no 'df' (dataframe)***

In [26]:
# Simplismente atribua o 'df' ao códgigo de formatação feita pro você

df = df.rename(columns={"country": "Pais", "continent": "Continente", "year": "Ano", "lifeExp": "Exp. de vida", "pop": "Pop. Total", "gdpPercap": "PIB"})

Testando se 'df' está alterado de fato:

In [24]:
df.head() # Sim. As 'colunas' estão em português:

          Pais Continente   Ano  Exp. de vida  Pop. Total         PIB
0  Afghanistan       Asia  1952        28.801     8425333  779.445314
1  Afghanistan       Asia  1957        30.332     9240934  820.853030
2  Afghanistan       Asia  1962        31.997    10267083  853.100710
3  Afghanistan       Asia  1967        34.020    11537966  836.197138
4  Afghanistan       Asia  1972        36.088    13079460  739.981106

--------------------------------------------------------------------------------------------------

# ***Retornando valores de um arquivo .csv***

--------------------------------------------------------------------------------------------------

## ***Retornando - Número de linhas e colunas que um arquivo possuí***

### shape

Retorna uma tupla com os valores que o arquivo dispõe.

(* número de linhas *, * número de colunas *)

Obs.: Perceba que o 'shape' não precisa dos parênteses '()' depois dele.

In [28]:
df.shape

(3312, 6)

--------------------------------------------------------------------------------------------------

## ***Retornando - Apenas os nomes das colunas***

### columns

Retorna uma tupla com uma lista com os valores que o arquivo dispõe e o seu tipo por último.

Obs.: Perceba que o 'columns' não precisa dos parênteses '()' depois dele.

In [29]:
df.columns

Index(['Pais', 'Continente', 'Ano', 'Exp. de vida', 'Pop. Total', 'PIB'], dtype='object')

## ***Retornando - Tipo de dado em cada coluna***

### dtypes

Retorna uma tabela com o nome de cada coluna e, ao lado, o seu tipo de cado que ele armazena.

Obs.: Perceba que o 'dtypes' não precisa dos parênteses '()' depois dele.

In [32]:
df.dtypes

Pais             object
Continente       object
Ano               int64
Exp. de vida    float64
Pop. Total        int64
PIB             float64
dtype: object

--------------------------------------------------------------------------------------------------

# ***Estatísticas***

--------------------------------------------------------------------------------------------------

## ***Estatísticas - Retornando uma descrição por meio de informações estatísicas sobre o nosso arquivo***

### describre()

Retorna uma tabela nova com essas informações, respeitando cada coluna do arquivo.

In [33]:
df.describe()

               Ano  Exp. de vida    Pop. Total            PIB
count  3312.000000   3312.000000  3.312000e+03    3312.000000
mean   1980.301630     65.246871  3.161489e+07   11317.115805
std      16.927294     11.768412  1.041193e+08   11369.142739
min    1950.000000     23.599000  5.941200e+04     241.165876
25%    1967.000000     58.337500  2.678572e+06    2514.625266
50%    1982.000000     69.610000  7.557218e+06    7838.505123
75%    1996.000000     73.657750  1.958522e+07   17357.879170
max    2007.000000     82.670000  1.318683e+09  113523.132900