# ***Utilizando a Base de Dados da AdventureWorks, da Microsoft.***

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

Definindo e estilo do gráfico:

In [15]:
plt.style.use("seaborn")

OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

## Criando nosso DataFrame

In [6]:
df = pd.read_excel("../datasets/AdventureWorks.xlsx")

## Visualizando as primeiras 5 linhas

In [8]:
df.head()

,Data Venda,Data Envio,ID Loja,ID Produto,ID Cliente,No. Venda,Custo Unitário,Preço Unitário,Quantidade,Valor Desconto,Valor Venda,Produto,Fabricante,Marca,Classe,Cor
0,2008-05-09,2008-05-29,199,384,18839,200805093CS607,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red
1,2008-05-12,2008-05-17,306,384,19051,200805123CS567,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red
2,2008-05-14,2008-05-20,306,384,19052,200805143CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red
3,2008-05-21,2008-05-27,306,384,19052,200805213CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red
4,2008-06-20,2008-06-27,306,384,19053,200806203CS586,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red

## Quantidade de linhas e colunas

In [9]:
df.shape

(904, 16)

## Verificando os tipos de dados

In [10]:
df.dtypes

Data Venda        datetime64[ns]
Data Envio        datetime64[ns]
ID Loja                    int64
ID Produto                 int64
ID Cliente                 int64
No. Venda                 object
Custo Unitário           float64
Preço Unitário           float64
Quantidade                 int64
Valor Desconto           float64
Valor Venda              float64
Produto                   object
Fabricante                object
Marca                     object
Classe                    object
Cor                       object
dtype: object

## Qual é a Receita total?

In [11]:
df["Valor Venda"].sum()

np.float64(5984606.1426)

## Criando uma nova coluna com o "Custo Total"

In [12]:
df["Custo Total"] = df["Custo Unitário"].mul(df["Quantidade"])

## Verificando o resultado utilizando uma amostra com método sample()

In [14]:
df.sample()

,Data Venda,Data Envio,ID Loja,ID Produto,ID Cliente,No. Venda,Custo Unitário,Preço Unitário,Quantidade,Valor Desconto,Valor Venda,Produto,Fabricante,Marca,Classe,Cor,Custo Total
16,2009-07-18,2009-07-23,306,384,19071,200907183CS760,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48

## Retornando o "Custo Total" arredondado - Qual é o "Custo Total"?

In [17]:
round(df["Custo Total"].sum(), 2)

np.float64(2486783.05)

## Criando a coluna 'Lucro Total' (Receita que é o 'Valor Venda' - 'Custo Total')

In [19]:
df["Lucro Total"] = df["Valor Venda"] - df["Custo Total"]

In [20]:
df.head()

,Data Venda,Data Envio,ID Loja,ID Produto,ID Cliente,No. Venda,Custo Unitário,Preço Unitário,Quantidade,Valor Desconto,Valor Venda,Produto,Fabricante,Marca,Classe,Cor,Custo Total,Lucro Total
0,2008-05-09,2008-05-29,199,384,18839,200805093CS607,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52
1,2008-05-12,2008-05-17,306,384,19051,200805123CS567,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52
2,2008-05-14,2008-05-20,306,384,19052,200805143CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52
3,2008-05-21,2008-05-27,306,384,19052,200805213CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52
4,2008-06-20,2008-06-27,306,384,19053,200806203CS586,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52

## Total de Lucro arredondado

In [ ]:
# Podemos fazer como no exemplo acima, ou podemos armazenar em uma variável
lucro_total = round(df["Lucro Total"].sum(), 2)

print(lucro_total)

3497823.09

## Criando uma coluna com 'Tempo_envio' -> Total de dias para enviar o produto

In [23]:
df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

In [24]:
df.head()

,Data Venda,Data Envio,ID Loja,ID Produto,ID Cliente,No. Venda,Custo Unitário,Preço Unitário,Quantidade,Valor Desconto,Valor Venda,Produto,Fabricante,Marca,Classe,Cor,Custo Total,Lucro Total,Tempo_envio
0,2008-05-09,2008-05-29,199,384,18839,200805093CS607,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,20 days
1,2008-05-12,2008-05-17,306,384,19051,200805123CS567,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,5 days
2,2008-05-14,2008-05-20,306,384,19052,200805143CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,6 days
3,2008-05-21,2008-05-27,306,384,19052,200805213CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,6 days
4,2008-06-20,2008-06-27,306,384,19053,200806203CS586,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,7 days

## Alterando a coluna 'Tempo_envio' em minutos 

Agora, queremos saber a média do tempo de envio para cada Marca, e para isso precisamos transformar a coluna Tempo_envio em minutos

In [ ]:
df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days # ou seja, extraia para mim apenas os dias

In [26]:
df.head()

,Data Venda,Data Envio,ID Loja,ID Produto,ID Cliente,No. Venda,Custo Unitário,Preço Unitário,Quantidade,Valor Desconto,Valor Venda,Produto,Fabricante,Marca,Classe,Cor,Custo Total,Lucro Total,Tempo_envio
0,2008-05-09,2008-05-29,199,384,18839,200805093CS607,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,20
1,2008-05-12,2008-05-17,306,384,19051,200805123CS567,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,5
2,2008-05-14,2008-05-20,306,384,19052,200805143CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,6
3,2008-05-21,2008-05-27,306,384,19052,200805213CS576,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,6
4,2008-06-20,2008-06-27,306,384,19053,200806203CS586,348.58,758.0,6,0.0,4548.0,Adventure Works Laptop15.4W M1548 Red,Adventure Works,Adventure Works,Regular,Red,2091.48,2456.52,7

## Verificando o tipo de coluna 'Tempo_envio' primeiro

In [27]:
df["Tempo_envio"].dtype

dtype('int64')

## Média do tempo de envio por 'Marca'

In [28]:
df.groupby("Marca")["Tempo_envio"].mean()

Marca
Adventure Works    8.663866
Contoso            8.470930
Fabrikam           8.510121
Name: Tempo_envio, dtype: float64

## Situação 4 - E se for necessário saber o 'Lucro Total' por ano e 'Marca'?

### Agrupar por ano e marca:

In [31]:
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro Total"].sum()

Data Venda  Marca
2008        Adventure Works    3.066412e+05
            Contoso            5.641600e+04
            Fabrikam           1.557021e+06
2009        Adventure Works    4.053951e+05
            Contoso            1.382590e+05
            Fabrikam           1.034091e+06
Name: Lucro Total, dtype: float64

Os valores estão quebrados. Vamos formata-los

### Formatação de números

In [32]:
pd.options.display.float_format = '{:20,.3f}'.format

Ao trazermos o código novamente:

In [33]:
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro Total"].sum()

Data Venda  Marca
2008        Adventure Works            306,641.160
            Contoso                     56,416.001
            Fabrikam                 1,557,020.550
2009        Adventure Works            405,395.080
            Contoso                    138,258.952
            Fabrikam                 1,034,091.350
Name: Lucro Total, dtype: float64

Os valores estarão corrigidos.

## ***Resetando o index - Formatação e retornando uma nova tabela com os valores tidos acima***

In [35]:
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro Total"].sum().reset_index()
lucro_ano

   Data Venda            Marca          Lucro Total
0        2008  Adventure Works          306,641.160
1        2008          Contoso           56,416.001
2        2008         Fabrikam        1,557,020.550
3        2009  Adventure Works          405,395.080
4        2009          Contoso          138,258.952
5        2009         Fabrikam        1,034,091.350

--------------------------------------------------------------------------------------------------

# ***Analizando arquivo***

## ***Missing Values***

In [29]:
df.isnull().sum()

Data Venda        0
Data Envio        0
ID Loja           0
ID Produto        0
ID Cliente        0
No. Venda         0
Custo Unitário    0
Preço Unitário    0
Quantidade        0
Valor Desconto    0
Valor Venda       0
Produto           0
Fabricante        0
Marca             0
Classe            0
Cor               0
Custo Total       0
Lucro Total       0
Tempo_envio       0
dtype: int64

Não há nenhum valor nulo.